apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: student-manager
spec:
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
        tier: backend
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9411
        envFrom:
          - configMapRef:
              name: zipkin-config
          - secretRef:
              name: zipkin-secret
      restartPolicy: Always
