FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml /app/pom.xml
COPY ./eureka-server/pom.xml /app/eureka-server/pom.xml
RUN mvn -f /app/eureka-server/pom.xml dependency:go-offline
COPY ./eureka-server/src /app/eureka-server/src
RUN mvn -f /app/eureka-server/pom.xml package

FROM openjdk:17.0.2-jdk
WORKDIR /app
COPY --from=build /app/eureka-server/target/eureka-server-1.0.jar eureka.jar
CMD java -jar eureka.jar