FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml /app/pom.xml
COPY ./api-gateway/pom.xml /app/api-gateway/pom.xml
RUN mvn -f /app/api-gateway/pom.xml dependency:go-offline
COPY ./api-gateway/src /app/api-gateway/src
RUN mvn -f /app/api-gateway/pom.xml package

FROM openjdk:17.0.2-jdk
WORKDIR /app
COPY --from=build /app/api-gateway/target/api-gateway-1.0.jar api-gateway.jar
ENV JAVA_OPTS=""
CMD java $JAVA_OPTS -jar api-gateway.jar