version: "3.9"
volumes:
  student-card-db:
  student-db:
services:
  student-card-db:
    image: postgres:14.2-alpine
    container_name: student-card-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=Password01!
      - POSTGRES_DB=student_card
    ports:
      - "5432:5432"
    volumes:
      - student-card-db:/var/lib/postgresql/data/

  student-db:
    image: postgres:14.2-alpine
    container_name: student-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=Password01!
      - POSTGRES_DB=student
    ports:
      - "5433:5432"
    volumes:
      - student-db:/var/lib/postgresql/data/

  eureka-server:
    build:
      dockerfile: Dockerfile-eureka
      context: ./
    container_name: eureka-server
    restart: always
    environment:
      - SERVER_PORT=8761
    ports:
      - "8761:8761"

  api-gateway:
    build:
      dockerfile: Dockerfile-apigateway
      context: ./
    container_name: api-gateway
    restart: always
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SERVER_PORT=8765
    ports:
      - "8765:8765"

  student-card:
    build:
      dockerfile: Dockerfile-studentcard
      context: ./
    restart: always
    depends_on:
      - eureka-server
      - student-card-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://student-card-db/student_card
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SERVER_PORT=8081
    ports:
      - "8080-8089:8081"

  student:
    build:
      dockerfile: Dockerfile-student
      context: ./
    restart: always
    depends_on:
      - eureka-server
      - student-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://student-db/student
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SERVER_PORT=8082
    ports:
      - "8090-8099:8082"
