version: "3.9"
services:
  eureka:
    build:
      dockerfile: Dockerfile-eureka
      context: ./
    container_name: eureka-server
    environment:
      - SERVER_PORT=8761
    ports:
      - "8761:8761"

  student_card:
    build:
      dockerfile: Dockerfile-studentcard
      context: ./
    container_name: student-card
    depends_on:
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/student_card
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://host.docker.internal:8761/eureka
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
