apiVersion: v1
kind: PersistentVolume
metadata:
  name: zipkin-db-pv
  namespace: student-manager
  labels:
    app: zipkin-db
spec:
  nodeName: minikube
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /k8s/zipkin-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zipkin-db-pvc
  namespace: student-manager
  labels:
    app: zipkin-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi