apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-card-db
  namespace: student-manager
spec:
  selector:
    matchLabels:
      app: student-card-db
  replicas: 1
  template:
    metadata:
      labels:
        app: student-card-db
        tier: database
    spec:
      containers:
      - name: student-card-db
        image: postgres:14.2-alpine
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: student-card-db-config
          - secretRef:
              name: student-card-db-secret
        volumeMounts:
          - mountPath: /var/lib/postgresql/data/
            name: student-card-db-data
      volumes:
        - name: student-card-db-data
          persistentVolumeClaim:
            claimName: student-card-db-pvc
      restartPolicy: Always