apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: student-manager
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: backend
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.10.2-management-alpine
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
          - secretRef:
              name: rabbitmq-secret
        volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
      restartPolicy: Always