apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: student-manager
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
  - port: 5672
    targetPort: 5672
    name: rabbit-port
  - port: 15672
    targetPort: 15672
    name: rabbit-ui-port
