spring:
  version: 2.6.6
  application:
    name: eureka-server
    version: 1.0

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"