apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-card
  namespace: student-manager
spec:
  selector:
    matchLabels:
      app: student-card
  replicas: 1
  template:
    metadata:
      labels:
        app: student-card
        tier: backend
    spec:
      containers:
      - name: student-card
        image: registry.gitlab.com/student262/student-manager-be/student-card:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        envFrom:
          - configMapRef:
              name: student-card-config
          - secretRef:
              name: student-card-secret
        volumeMounts:
          - mountPath: /app/logs
            name: log-volume
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-pvc
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: Always