spring:
  version: 2.6.6
  application:
    name: config-server
    version: 1.0
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/student262/student-manager-config.git
          username: TheAppleGeeK
          password: glpat-DxzszDxSghbQWsqJzcz9
          default-label: main

server:
  port: 8888

logging:
  file.name: './logs/config-server.log'
  level:
    org.springframework.cloud: info
  logback:
    rolling policy:
      max-file-size: 100MB