spring:
  #==========================================================
  #= SPRING APPLICATION
  #==========================================================
  version: 2.6.6
  application:
    name: config-server
    version: 1.0
  #==========================================================
  #= SPRING CLOUD CONFIG SERVER WITH GIT
  #==========================================================
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/student262/student-manager-config.git
          username: TheAppleGeeK
          password: glpat-DxzszDxSghbQWsqJzcz9
          default-label: main

#==========================================================
#= SERVER
#==========================================================
server:
  port: 8888

#==========================================================
#= LOGGING
#==========================================================
logging:
  file.name: './logs/config-server.log'
  level:
    org.springframework.cloud: info
  logback:
    rolling policy:
      max-file-size: 100MB

#==============================================================
#= SPRING ACTUATOR
#==============================================================
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics

#==============================================================
#= SPRING ACTUATOR INFO
#==============================================================
info:
  application:
    name: ${spring.application.name}
    version: ${spring.application.version}
    spring-version: ${spring.version}
  support:
    author: "TheAppleGeeK"
    mail: "weibin.xu.dev@gmail.com"