apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: student-manager
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
        tier: backend
    spec:
      containers:
      - name: config-server
        image: registry.gitlab.com/student262/student-manager-be/config-server:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888
        envFrom:
          - configMapRef:
              name: config-server-config
          - secretRef:
              name: config-server-secret
        volumeMounts:
          - mountPath: /app/logs
            name: log-volume
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-pvc
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: Always